from glob import glob
import random
from typing import KeysView
from bs4 import BeautifulSoup
from PIL import Image
import os
import csv
  

events = []
with open('content.csv', mode='r') as inp:
    reader = csv.reader(inp)
    events = list(reader)

html = BeautifulSoup("<!--Autogenerated HTML--><div class='verticalLine'></div>", 'html.parser')

for event in events:
    eventContainer = html.new_tag('div')
    eventContainer['class'] = 'eventContainer'
    eventContainer['style'] = 'top: '+str(round(int(event[0])/1000)) + "px"

    eventImg = html.new_tag('div')
    eventImg['class'] = 'eventImg'

    img = html.new_tag('img')
    img['src'] = "./images/" + event[3]

    eventImg.append(img)

    eventLine = html.new_tag('div')
    eventLine['class'] = 'eventLine'

    eventTitle = html.new_tag('div')
    eventTitle['class'] = 'eventTitle'
    eventTitle.string = event[1]

    eventText = html.new_tag('div')
    eventText['class'] = 'eventText'
    eventText.string = event[2]

    nextEvent = html.new_tag('div')
    nextEvent['class'] = 'nextEvent'
    nextEvent.string = 'Next Event'

    eventContainer.append(eventImg)
    eventContainer.append(eventLine)
    eventContainer.append(eventTitle)
    eventContainer.append(eventText)
    eventContainer.append(nextEvent)
    html.append(eventContainer)


with open('events.html', 'w') as f:
    f.write(str(html.prettify()))

